0$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('217','104','%id%', '%world%')$
0$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','217','104','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3481','100','1672','1', 'Ile-%id%', '1000')$
1$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('217','106','%id%', '%world%')$
1$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','217','106','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3477','100','1706','1', 'Ile-%id%', '1000')$
2$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('215','108','%id%', '%world%')$
2$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','215','108','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3447','100','1735','1', 'Ile-%id%', '1000')$
3$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('213','108','%id%', '%world%')$
3$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','213','108','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3415','100','1736','1', 'Ile-%id%', '1000')$
4$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('215','110','%id%', '%world%')$
4$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','215','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3446','100','1768','1', 'Ile-%id%', '1000')$
5$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('213','110','%id%', '%world%')$
5$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','213','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3414','100','1768','1', 'Ile-%id%', '1000')$
6$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('211','110','%id%', '%world%')$
6$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','211','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3383','100','1770','1', 'Ile-%id%', '1000')$
7$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('211','112','%id%', '%world%')$
7$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','211','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3381','86','1802','1', 'Ile-%id%', '1000')$
8$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('213','112','%id%', '%world%')$
8$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','213','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3415','86','1801','1', 'Ile-%id%', '1000')$
9$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('215','112','%id%', '%world%')$
9$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','215','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3447','86','1801','1', 'Ile-%id%', '1000')$
10$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('213','114','%id%', '%world%')$
10$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','213','114','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3417','87','1832','1', 'Ile-%id%', '1000')$
11$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('215','114','%id%', '%world%')$
11$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','215','114','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3448','86','1834','1', 'Ile-%id%', '1000')$
12$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('217','116','%id%', '%world%')$
12$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','217','116','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3479','86','1866','1', 'Ile-%id%', '1000')$
13$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('217','118','%id%', '%world%')$
13$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','217','118','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3479','87','1896','1', 'Ile-%id%', '1000')$
14$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('219','120','%id%', '%world%')$
14$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','219','120','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3511','86','1929','1', 'Ile-%id%', '1000')$
15$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('221','120','%id%', '%world%')$
15$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','221','120','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3542','86','1930','1', 'Ile-%id%', '1000')$
16$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('223','118','%id%', '%world%')$
16$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','223','118','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3574','86','1899','1', 'Ile-%id%', '1000')$
17$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('223','116','%id%', '%world%')$
17$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','223','116','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3576','85','1867','1', 'Ile-%id%', '1000')$
18$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('225','114','%id%', '%world%')$
18$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','225','114','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3603','90','1835','1', 'Ile-%id%', '1000')$
19$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('227','114','%id%', '%world%')$
19$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','227','114','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3637','91','1835','1', 'Ile-%id%', '1000')$
20$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('225','112','%id%', '%world%')$
20$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','225','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3606','91','1804','1', 'Ile-%id%', '1000')$
21$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('227','112','%id%', '%world%')$
21$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','227','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3637','90','1802','1', 'Ile-%id%', '1000')$
22$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('229','112','%id%', '%world%')$
22$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','229','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3665','90','1803','1', 'Ile-%id%', '1000')$
23$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('225','110','%id%', '%world%')$
23$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','225','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3609','91','1772','1', 'Ile-%id%', '1000')$
24$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('227','110','%id%', '%world%')$
24$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','227','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3639','91','1771','1', 'Ile-%id%', '1000')$
25$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('229','110','%id%', '%world%')$
25$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','229','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3673','101','1768','1', 'Ile-%id%', '1000')$
26$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('225','108','%id%', '%world%')$
26$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','225','108','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3605','91','1738','1', 'Ile-%id%', '1000')$
27$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('227','108','%id%', '%world%')$
27$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','227','108','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3637','91','1738','1', 'Ile-%id%', '1000')$
28$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('223','106','%id%', '%world%')$
28$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','223','106','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3577','91','1707','1', 'Ile-%id%', '1000')$
29$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('223','104','%id%', '%world%')$
29$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','223','104','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3572','90','1677','1', 'Ile-%id%', '1000')$
30$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('221','102','%id%', '%world%')$
30$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','221','102','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3546','90','1645','1', 'Ile-%id%', '1000')$
31$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('219','102','%id%', '%world%')$
31$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','219','102','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3510','86','1643','1', 'Ile-%id%', '1000')$
32$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('217','104','%id%', '%world%')$
32$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','217','104','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3480','86','1669','1', 'Ile-%id%', '1000')$
33$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('217','106','%id%', '%world%')$
33$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','0','217','106','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3478','85','1699','1', 'Ile-%id%', '1000')$
34$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('211','107','%id%', '%world%')$
34$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','211','107','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3377','92','1726','1', 'Ile-%id%', '10000')$
34$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('210','107','%id%', '%world%')$
34$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','210','107','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3374','92','1726','1', 'Ile-%id%', '10000')$
34$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('210','108','%id%', '%world%')$
34$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','210','108','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3374','92','1728','1', 'Ile-%id%', '10000')$
34$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('211','108','%id%', '%world%')$
34$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','211','108','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3376','91','1729','1', 'Ile-%id%', '10000')$
35$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('214','106','%id%', '%world%')$
35$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','214','106','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3439','90','1696','1', 'Ile-%id%', '10000')$
35$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('214','105','%id%', '%world%')$
35$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','214','105','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3439','90','1694','1', 'Ile-%id%', '10000')$
35$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('215','105','%id%', '%world%')$
35$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','215','105','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3440','90','1695','1', 'Ile-%id%', '10000')$
35$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('215','106','%id%', '%world%')$
35$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','215','106','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3440','90','1697','1', 'Ile-%id%', '10000')$
36$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('216','102','%id%', '%world%')$
36$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','216','102','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3470','94','1632','1', 'Ile-%id%', '10000')$
36$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('216','101','%id%', '%world%')$
36$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','216','101','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3470','94','1631','1', 'Ile-%id%', '10000')$
36$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('217','101','%id%', '%world%')$
36$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','217','101','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3472','94','1630','1', 'Ile-%id%', '10000')$
36$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('217','102','%id%', '%world%')$
36$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','217','102','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3472','93','1633','1', 'Ile-%id%', '10000')$
37$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('223','101','%id%', '%world%')$
37$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','223','101','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3582','89','1630','1', 'Ile-%id%', '10000')$
37$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('224','101','%id%', '%world%')$
37$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','224','101','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3584','89','1630','1', 'Ile-%id%', '10000')$
37$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('224','102','%id%', '%world%')$
37$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','224','102','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3584','89','1632','1', 'Ile-%id%', '10000')$
37$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('223','102','%id%', '%world%')$
37$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','223','102','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3582','88','1633','1', 'Ile-%id%', '10000')$
38$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('225','105','%id%', '%world%')$
38$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','225','105','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3614','90','1694','1', 'Ile-%id%', '10000')$
38$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('226','105','%id%', '%world%')$
38$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','226','105','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3616','90','1694','1', 'Ile-%id%', '10000')$
38$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('226','106','%id%', '%world%')$
38$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','226','106','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3617','90','1696','1', 'Ile-%id%', '10000')$
38$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('225','106','%id%', '%world%')$
38$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','225','106','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3615','89','1697','1', 'Ile-%id%', '10000')$
39$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('229','107','%id%', '%world%')$
39$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','229','107','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3678','90','1727','1', 'Ile-%id%', '10000')$
39$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('230','107','%id%', '%world%')$
39$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','230','107','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3681','90','1727','1', 'Ile-%id%', '10000')$
39$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('230','108','%id%', '%world%')$
39$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','230','108','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3682','90','1729','1', 'Ile-%id%', '10000')$
39$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('229','108','%id%', '%world%')$
39$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','229','108','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3679','89','1729','1', 'Ile-%id%', '10000')$
40$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('230','114','%id%', '%world%')$
40$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','230','114','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3680','93','1838','1', 'Ile-%id%', '10000')$
40$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('230','115','%id%', '%world%')$
40$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','230','115','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3680','93','1841','1', 'Ile-%id%', '10000')$
40$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('229','115','%id%', '%world%')$
40$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','229','115','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3679','92','1840','1', 'Ile-%id%', '10000')$
41$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('226','116','%id%', '%world%')$
41$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','226','116','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3617','90','1870','1', 'Ile-%id%', '10000')$
41$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('226','117','%id%', '%world%')$
41$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','226','117','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3617','90','1872','1', 'Ile-%id%', '10000')$
41$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('225','117','%id%', '%world%')$
41$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','225','117','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3614','90','1872','1', 'Ile-%id%', '10000')$
41$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('225','116','%id%', '%world%')$
41$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','225','116','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3614','90','1870','1', 'Ile-%id%', '10000')$
42$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('224','120','%id%', '%world%')$
42$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','224','120','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3584','95','1935','1', 'Ile-%id%', '10000')$
42$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('223','120','%id%', '%world%')$
42$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','223','120','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3582','95','1935','1', 'Ile-%id%', '10000')$
42$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('223','121','%id%', '%world%')$
42$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','223','121','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3583','94','1936','1', 'Ile-%id%', '10000')$
42$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('224','121','%id%', '%world%')$
42$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','224','121','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3585','95','1937','1', 'Ile-%id%', '10000')$
43$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('217','120','%id%', '%world%')$
43$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','217','120','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3473','92','1934','1', 'Ile-%id%', '10000')$
43$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('217','121','%id%', '%world%')$
43$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','217','121','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3472','92','1937','1', 'Ile-%id%', '10000')$
43$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('216','121','%id%', '%world%')$
43$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','216','121','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3470','92','1936','1', 'Ile-%id%', '10000')$
43$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('216','120','%id%', '%world%')$
43$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','216','120','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3470','92','1934','1', 'Ile-%id%', '10000')$
44$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('214','117','%id%', '%world%')$
44$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','214','117','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3437','90','1873','1', 'Ile-%id%', '10000')$
44$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('214','116','%id%', '%world%')$
44$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','214','116','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3437','90','1870','1', 'Ile-%id%', '10000')$
44$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('215','116','%id%', '%world%')$
44$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','215','116','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3440','90','1870','1', 'Ile-%id%', '10000')$
44$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('215','117','%id%', '%world%')$
44$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','215','117','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3441','90','1872','1', 'Ile-%id%', '10000')$
45$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('211','114','%id%', '%world%')$
45$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','211','114','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3377','86','1839','1', 'Ile-%id%', '10000')$
45$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('211','115','%id%', '%world%')$
45$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','211','115','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3377','86','1841','1', 'Ile-%id%', '10000')$
45$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('210','115','%id%', '%world%')$
45$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','210','115','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3372','86','1840','1', 'Ile-%id%', '10000')$
45$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('210','114','%id%', '%world%')$
45$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','1','210','114','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3373','86','1839','1', 'Ile-%id%', '10000')$
46$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('209','112','%id%', '%world%')$
46$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','209','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3350','95','1798','1', 'Ile-%id%', '50000')$
46$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('209','111','%id%', '%world%')$
46$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','209','111','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3350','98','1783','1', 'Ile-%id%', '50000')$
46$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('209','110','%id%', '%world%')$
46$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','209','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3350','98','1766','1', 'Ile-%id%', '50000')$
46$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('208','110','%id%', '%world%')$
46$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','208','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3341','98','1771','1', 'Ile-%id%', '50000')$
46$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('208','111','%id%', '%world%')$
46$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','208','111','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3340','98','1779','1', 'Ile-%id%', '50000')$
46$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('208','112','%id%', '%world%')$
46$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','208','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3340','98','1796','1', 'Ile-%id%', '50000')$
46$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('207','112','%id%', '%world%')$
46$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','207','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3322','98','1798','1', 'Ile-%id%', '50000')$
46$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('207','111','%id%', '%world%')$
46$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','207','111','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3319','98','1790','1', 'Ile-%id%', '50000')$
46$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('207','110','%id%', '%world%')$
46$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','207','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3317','98','1772','1', 'Ile-%id%', '50000')$
47$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('219','106','%id%', '%world%')$
47$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','219','106','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3507','98','1700','1', 'Ile-%id%', '50000')$
47$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('219','105','%id%', '%world%')$
47$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','219','105','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3508','98','1693','1', 'Ile-%id%', '50000')$
47$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('219','104','%id%', '%world%')$
47$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','219','104','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3506','98','1676','1', 'Ile-%id%', '50000')$
47$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('220','104','%id%', '%world%')$
47$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','220','104','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3522','98','1669','1', 'Ile-%id%', '50000')$
47$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('221','104','%id%', '%world%')$
47$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','221','104','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3538','98','1670','1', 'Ile-%id%', '50000')$
47$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('221','105','%id%', '%world%')$
47$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','221','105','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3539','98','1686','1', 'Ile-%id%', '50000')$
47$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('220','105','%id%', '%world%')$
47$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','220','105','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3528','98','1690','1', 'Ile-%id%', '50000')$
47$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('220','106','%id%', '%world%')$
47$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','220','106','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3532','98','1701','1', 'Ile-%id%', '50000')$
47$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('221','106','%id%', '%world%')$
47$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','221','106','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3543','98','1697','1', 'Ile-%id%', '50000')$
48$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('231','112','%id%', '%world%')$
48$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','231','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3701','98','1799','1', 'Ile-%id%', '50000')$
48$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('232','112','%id%', '%world%')$
48$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','232','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3723','98','1802','1', 'Ile-%id%', '50000')$
48$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('233','112','%id%', '%world%')$
48$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','233','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3732','98','1796','1', 'Ile-%id%', '50000')$
48$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('233','111','%id%', '%world%')$
48$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','233','111','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3732','98','1785','1', 'Ile-%id%', '50000')$
48$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('232','111','%id%', '%world%')$
48$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','232','111','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3722','98','1784','1', 'Ile-%id%', '50000')$
48$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('233','110','%id%', '%world%')$
48$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','233','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3734','98','1767','1', 'Ile-%id%', '50000')$
48$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('232','110','%id%', '%world%')$
48$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','232','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3722','98','1768','1', 'Ile-%id%', '50000')$
48$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('231','110','%id%', '%world%')$
48$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','231','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3701','98','1770','1', 'Ile-%id%', '50000')$
48$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('231','111','%id%', '%world%')$
48$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','231','111','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3699','98','1784','1', 'Ile-%id%', '50000')$
49$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('221','118','%id%', '%world%')$
49$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','221','118','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3543','98','1896','1', 'Ile-%id%', '50000')$
49$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('220','118','%id%', '%world%')$
49$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','220','118','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3524','98','1895','1', 'Ile-%id%', '50000')$
49$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('219','118','%id%', '%world%')$
49$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','219','118','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3516','98','1895','1', 'Ile-%id%', '50000')$
49$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('219','117','%id%', '%world%')$
49$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','219','117','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3510','98','1876','1', 'Ile-%id%', '50000')$
49$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('219','116','%id%', '%world%')$
49$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','219','116','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3512','98','1866','1', 'Ile-%id%', '50000')$
49$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('220','116','%id%', '%world%')$
49$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','220','116','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3527','98','1863','1', 'Ile-%id%', '50000')$
49$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('221','116','%id%', '%world%')$
49$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','221','116','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3544','98','1863','1', 'Ile-%id%', '50000')$
49$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('221','117','%id%', '%world%')$
49$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','221','117','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3540','98','1880','1', 'Ile-%id%', '50000')$
49$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('220','117','%id%', '%world%')$
49$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','2','220','117','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3532','98','1884','1', 'Ile-%id%', '50000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('222','113','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','222','113','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3562','98','1815','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('223','113','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','223','113','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3574','98','1817','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('223','112','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','223','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3573','98','1801','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('223','111','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','223','111','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3574','98','1786','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('223','110','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','223','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3575','98','1769','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('223','109','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','223','109','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3576','98','1752','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('223','108','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','223','108','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3576','98','1739','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('222','108','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','222','108','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3559','98','1740','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('221','108','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','221','108','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3548','98','1736','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('220','108','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','220','108','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3527','98','1736','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('219','108','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','219','108','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3510','98','1737','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('218','108','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','218','108','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3497','98','1736','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('217','108','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','217','108','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3481','98','1736','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('217','109','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','217','109','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3480','98','1749','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('217','110','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','217','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3478','98','1763','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('217','111','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','217','111','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3478','98','1782','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('217','112','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','217','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3478','98','1797','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('217','113','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','217','113','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3478','98','1813','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('217','114','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','217','114','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3478','98','1829','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('218','114','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','218','114','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3494','98','1832','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('219','114','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','219','114','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3510','98','1828','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('220','114','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','220','114','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3530','98','1830','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('221','114','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','221','114','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3539','98','1830','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('222','114','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','222','114','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3556','98','1827','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('223','114','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','223','114','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3570','98','1830','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('221','113','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','221','113','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3545','98','1814','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('220','113','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','220','113','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3529','98','1811','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('219','113','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','219','113','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3510','98','1815','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('218','112','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','218','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3489','98','1805','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('218','113','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','218','113','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3499','98','1814','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('219','112','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','219','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3509','98','1803','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('220','112','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','220','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3528','98','1803','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('221','112','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','221','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3545','98','1802','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('222','112','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','222','112','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3562','98','1800','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('222','111','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','222','111','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3562','98','1787','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('221','111','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','221','111','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3543','98','1785','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('220','111','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','220','111','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3531','98','1785','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('219','111','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','219','111','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3515','98','1785','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('218','111','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','218','111','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3499','98','1780','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('218','110','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','218','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3502','98','1769','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('219','110','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','219','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3515','98','1768','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('220','110','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','220','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3531','98','1767','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('221','110','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','221','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3543','98','1767','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('222','110','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','222','110','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3562','98','1766','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('222','109','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','222','109','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3563','98','1753','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('221','109','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','221','109','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3540','98','1752','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('220','109','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','220','109','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3528','98','1753','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('219','109','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','219','109','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3516','98','1753','1', 'Ile-%id%', '100000')$
50$INSERT INTO `Neo-Stage-Chunk`(`PosX`, `PosZ`, `IdStage`, `IdWorld`) VALUES ('218','109','%id%', '%world%')$
50$INSERT INTO `Neo-Stage`(`id2`, `WorldId`, `StageId`, `XPos`, `ZPos`, `PermAll`, `PermMember`, `isUse`,`x`,`y`,`z`, `hasHome`,`name`, `bank`) VALUES ('%id%','%world%','3','218','109','enderpearl&attaque&','enderpearl&attaque&bonemeal&block&container&harvest&interact&','0','3496','98','1753','1', 'Ile-%id%', '100000')$
